### ISSUE TITLE
Unable to save deployment folder

### ISSUE THREAD

**Issue by ck-intel** [openvinotoolkit/geti-sdk#168]
geti-sdk version - 1.2.2
GETi version - 1.0.1

All the artefacts of deployment folder are not saved properly if saved using a separate function call, please refer the code below:

`def save():`  
`   deployment = geti.deploy_project(project_name="m1_demo")`
`   deployment.save("./")`
`save()`

@ljcornel  Looks like the fix to delete temporary deployment folder is deleting the artefacts in this case too.

**Comment by ljcornel** [comment]
Should be fixed in [PR 170](https://github.com/openvinotoolkit/geti-sdk/pull/170)

**Comment by ljcornel** [comment]
Fix confirmed, thanks again for reporting @ck-intel!
