### ISSUE TITLE
Failed building wheel for Datumaro

### ISSUE THREAD

**Issue by paularamo** [openvinotoolkit/geti-sdk#181]
I haven't had any this issue before. Are the requirements changed?
![image](https://user-images.githubusercontent.com/10940214/229528421-66903414-dd1c-4939-85be-8b9515a9cf52.png)

**Comment by ljcornel** [comment]
Thanks for reporting this issue, indeed the datumaro requirement has changed from v0.5 to v1.0. I'll have a look

**Comment by ljcornel** [comment]
This issue should be resolved now, the `datumaro` package now has uploaded wheels for windows installation to PyPI. This means that it is no longer necessary to build datumaro locally when installing `geti-sdk`.
