### ISSUE TITLE
pre-commit failed in python3.8

### ISSUE THREAD

**Issue by jihyeonyi** [openvinotoolkit/geti-sdk#234]
When using python3.8, pre-commit failed due to the run-time error when installing isort.
The change of poetry-core caused an incompatibility with isort.
This can be fixed by upgrading isort version to v5.12.0 in the pre-commit yaml file.

**Comment by ljcornel** [comment]
Thanks for reporting this issue and creating a PR to fix it right away, @jihyeonyi! Really appreciate it.
