### ISSUE TITLE
Cannot find the Intel Geti platform Server

### ISSUE THREAD

**Issue by TranThanhTan19146259** [openvinotoolkit/geti-sdk#236]
I have searched the document about how to use Geti and it required me an access token from Geti Server.
Could you show me the link to get this token?
![image](https://github.com/openvinotoolkit/geti-sdk/assets/95736641/9207be49-150b-4f40-8ba7-728a3a86c376)

Thank you!

**Comment by ljcornel** [comment]
Hi, and thank you for your interest in the Intel Geti platform! 

At the moment we don't provide any public Intel Geti servers, however if you are interested in trying the platform please drop a message at [the Intel Geti contact page](https://geti.intel.com/contact-us). The support team will then reach out to you to discuss the possibilities and see how we can help you out.
