### ISSUE TITLE
Deployment issues using intel openvino(geti_sdk)

### ISSUE THREAD

**Issue by nomanmazharr** [openvinotoolkit/geti-sdk#284]
While deploying using geti_sdk i am able to install and import it successfuly but during getting server_details_from_environment i am getting error;

**ValueError: Unable to load Geti Server details from environment file at path '.env', please make sure the file exists.**

In my case I am not able to find .env file as its not generated by geti-sdk. I tried to create a .txt file with name .env but still not able to resolve the issue.
Please help me resolve it.

**Comment by ljcornel** [comment]
Hi, please have a look at the instructions for running the Jupyter notebooks. It contains a paragraph on how to set up your `.env` file [here](https://github.com/openvinotoolkit/geti-sdk/tree/main/notebooks#setting-things-up )
