### ISSUE TITLE
Download Annotated Data

### ISSUE THREAD

**Issue by nomanmazharr** [openvinotoolkit/geti-sdk#286]
Is there a way to download annotated data in Geti? Annotations can be a time-consuming process, and having the option to download them would be greatly beneficial.

**Comment by ljcornel** [comment]
Hi @nomanmazharr, yes you can indeed download your annotated data. Have a look at [this notebook](https://github.com/openvinotoolkit/geti-sdk/blob/main/notebooks/009_download_and_upload_project.ipynb), which shows how to download a project from Geti. This will include all your annotations.
