### ISSUE TITLE
Authentication via your personal access token has failed, most likely the token has expired

### ISSUE THREAD

**Issue by BeBi18** [openvinotoolkit/geti-sdk#422]
I am currently attempting to set up my local environment to connect with the Intel Geti platform using the provided SDK. I have configured my .env file with the necessary details, but I am encountering issues when trying to establish a connection.

Here is the content of my .env file for reference:
HOST=  URL to my workspaces geti intel
HTTPS_PROXY= https_proxy
TOKEN= Personal Access Token
VERIFY_CERT=0

I believe the HOST variable should be the URL to my workspace on the Intel Geti platform. Could you please confirm if this understanding is correct?

I have authentication error when using my personal access token. The error message states: "Authentication via your personal access token has failed, most likely the token has expired." This is confusing because I have just created the token, and it should not be expired. 
Upon further inspection, I noticed that the token does not seem to be included in the request parameters. Could you check it again?

Are there any additional steps I need to take to ensure the token is recognized and not flagged as expired?

My ServerTokenConfig
ServerTokenConfig(host= URL to my workspaces geti intel, has_valid_certificate=False, proxies={'https': 'http://proxy.../'}, token='Personal Access Token')

Thank you for your time and support @ljcornel .

Best regards.

**Comment by ljcornel** [comment]
Hi @BeBi18, thanks for reaching out! Could you copy the stacktrace for the error you're getting? From your post it seems that you are following the correct procedure to connect, so it is hard for me to debug without additional details.

Please reach me by email/teams with more information, that way I can help you further.

**Comment by ljcornel** [comment]
Closed after further discussion through private channel
