### ISSUE TITLE
Any idea of what should I use in HOST for the .env file?

### ISSUE THREAD

**Issue by ChellShort** [openvinotoolkit/geti-sdk#525]
Hello, I'm new in the use of this SDK and I want  it for the use of a model that I made in Intel Geti. 

Once i finished the creation of the virtual environment and the .env file for the use of the notebooks, I encountered many errors about the definiton of the HOST of the Geti server to run it locally, saying that it cannot reach the ip address, I tried to put my actual IP, despite that it still fails, then I tried mounting a local server with apache and trying to transform it to https with ngrok, but it didn't work.

Am I doing something awfully wrong? Do I need to install any other tool for the server deployment?, if yes, wich one?

**Comment by leoll2** [comment]
Hi @ChellShort, the `HOST` variable should point to the address of your Geti instance, including the protocol (e.g. `https://10.20.30.40` or `https://foo.bar.com`). If that address cannot be reached, it could depend on various reasons. As a sanity check, have you tried to ping the target server? 

Depending on your network configuration, you may also need to specify a proxy:  [here](https://github.com/openvinotoolkit/geti-sdk/blob/9960040499b9b7a5d84feea99bebfa779b03b0f9/geti_sdk/http_session/server_config.py#L46) is an example of value, you can also pass it directly to the `Geti` client (see [here](https://github.com/openvinotoolkit/geti-sdk/blob/9960040499b9b7a5d84feea99bebfa779b03b0f9/geti_sdk/geti.py#L119)).

If you still can't reach your Geti instance after trying the above suggestions, please share details about your Geti installation adn network setup, and also the exact error message returned by the Geti SDK.

**Comment by ChellShort** [comment]
Hello, thanks for the help @leoll2, I'm gonna try to explain my problem the best I can, if anyone needs to know something else, please, let me know.

In this case, the host that I'm trying to reach is my own IP, I can reach it without problems with ping.
![Captura de pantalla 2024-12-11 094959](https://github.com/user-attachments/assets/66abf820-d6cf-4665-9761-eadca6db5e0b)
When it comes to the server, i don't have one, like I said, I'm trying to do it locally first, Anyway, when i try to run the notebooks example with my own IP, i get this error:

Running the 001_create_project notebook
![image](https://github.com/user-attachments/assets/a1841a38-3c86-40da-96a6-cc25ddeff800)
![image](https://github.com/user-attachments/assets/9d952534-7959-49ff-a9bd-5959bf90cf38)
![image](https://github.com/user-attachments/assets/03d26870-0b31-4e37-811d-3d743ca5173c)
![image](https://github.com/user-attachments/assets/e1704b72-513b-499a-8c26-dda7dfe02ed0)

![image](https://github.com/user-attachments/assets/89cbc8db-2045-4b62-9e51-9f91c81fe0c5) In this .env file i do not include the port.

I'm confused about the address of the Geti Instance, do you refer to the IP of the localhost that is made when the Jupyter Lab is launched, my own IP or any other one?, I know that in the documentation it says that you can use your IP or  your server hostname, but honestly I'm lost.

**Comment by leoll2** [comment]
> When it comes to the server, i don't have one, like I said, I'm trying to do it locally first

I think this might be the problem. As the README says:

> The Intel® Geti™ SDK is a python package which contains tools to interact with an Intel® Geti™ server via the REST API.

The Geti SDK is a Python client to interact with a Geti server, but it does NOT include the server itself. Installing Geti locally (on-premise) is possible, provided you have a license: please refer to the [website](https://geti.intel.com/) or the [documentation](https://docs.geti.intel.com/) for more details.

**Comment by ChellShort** [comment]
Hello I didn't figured out what was wrong with the use of the notebooks, but I already found a way to use locally the model developed in the Intel Geti platform.

In the deployment folder there's a couple of python examples of how to use the model and some example jupyter notebooks.
![image](https://github.com/user-attachments/assets/09e26530-51df-4ede-9168-eb7da4807215)
![image](https://github.com/user-attachments/assets/4e3f2fc1-8433-41ed-982a-706fd7d96896)
![image](https://github.com/user-attachments/assets/6c2f8611-ea42-4cc6-9006-4f586b476874)

This is what I wanted to achieve, so this is enough, but the problem now is that the demonstration of the use of OpenVino Model Server does not seem to work, because it does not give any result. 

Should I add this as an issue in this repository or i need to refer to other one?

**Comment by ChellShort** [comment]
Hello I didn't figured out what was wrong with the use of the notebooks, but I already found a way to use locally the model developed in the Intel Geti platform.

In the deployment folder there's a couple of python examples of how to use the model and some example jupyter notebooks.
![image](https://github.com/user-attachments/assets/404c80bc-25e7-4421-bc52-a73ba09376a1)
![image](https://github.com/user-attachments/assets/9d026cfe-dfdd-4348-82ba-99277efe6f51)
![image](https://github.com/user-attachments/assets/6e80a5a3-89e4-4d99-aab0-1c7e79a934f8)

This is what I wanted to achieve, but the problem now is that the demonstration of the use of OpenVino Model Server does not seem to work, because it does not give any result. 

Should I add this as an issue in this repository or i need to refer to other one?

**Comment by leoll2** [comment]
> This is what I wanted to achieve, but the problem now is that the demonstration of the use of OpenVino Model Server does not seem to work, because it does not give any result in the inference.
Should I add this as an issue in this repository or i need to refer to other one?

Hello again @ChellShort, for this issue I recommend you use the "contact support" button in the Geti UI, or go directly to the [support page](https://supporttickets.intel.com/s/supportrequest?language=en_US).

![image](https://github.com/user-attachments/assets/e07310d1-2f15-4508-a44c-a5615294ff37)

**Comment by ChellShort** [comment]
Thanks for the help @leoll2, I already sent the problem to the support of the tool, I hope I get a reponse, for the moment I'm gonna close this issue, because the main goal was fullfiled, again, thanks for all the help.
